#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formjdrppe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="projet_prosql")]
	public partial class basejdrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertPERSO_OBJET(PERSO_OBJET instance);
    partial void UpdatePERSO_OBJET(PERSO_OBJET instance);
    partial void DeletePERSO_OBJET(PERSO_OBJET instance);
    partial void InsertPERSO_COMP(PERSO_COMP instance);
    partial void UpdatePERSO_COMP(PERSO_COMP instance);
    partial void DeletePERSO_COMP(PERSO_COMP instance);
    partial void InsertJOUEUR(JOUEUR instance);
    partial void UpdateJOUEUR(JOUEUR instance);
    partial void DeleteJOUEUR(JOUEUR instance);
    partial void InsertPARTIE(PARTIE instance);
    partial void UpdatePARTIE(PARTIE instance);
    partial void DeletePARTIE(PARTIE instance);
    partial void InsertPERSO_PARTIE(PERSO_PARTIE instance);
    partial void UpdatePERSO_PARTIE(PERSO_PARTIE instance);
    partial void DeletePERSO_PARTIE(PERSO_PARTIE instance);
    partial void InsertCLASSE(CLASSE instance);
    partial void UpdateCLASSE(CLASSE instance);
    partial void DeleteCLASSE(CLASSE instance);
    partial void InsertRACE(RACE instance);
    partial void UpdateRACE(RACE instance);
    partial void DeleteRACE(RACE instance);
    partial void InsertCOMPETENCE(COMPETENCE instance);
    partial void UpdateCOMPETENCE(COMPETENCE instance);
    partial void DeleteCOMPETENCE(COMPETENCE instance);
    partial void InsertOBJET_RARE(OBJET_RARE instance);
    partial void UpdateOBJET_RARE(OBJET_RARE instance);
    partial void DeleteOBJET_RARE(OBJET_RARE instance);
    partial void InsertOBJET(OBJET instance);
    partial void UpdateOBJET(OBJET instance);
    partial void DeleteOBJET(OBJET instance);
    partial void InsertPERSONNAGE(PERSONNAGE instance);
    partial void UpdatePERSONNAGE(PERSONNAGE instance);
    partial void DeletePERSONNAGE(PERSONNAGE instance);
    #endregion
		
		public basejdrDataContext() : 
				base(global::formjdrppe.Properties.Settings.Default.projet_prosqlConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public basejdrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basejdrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basejdrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basejdrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PERSO_OBJET> PERSO_OBJET
		{
			get
			{
				return this.GetTable<PERSO_OBJET>();
			}
		}
		
		public System.Data.Linq.Table<PERSO_COMP> PERSO_COMP
		{
			get
			{
				return this.GetTable<PERSO_COMP>();
			}
		}
		
		public System.Data.Linq.Table<JOUEUR> JOUEUR
		{
			get
			{
				return this.GetTable<JOUEUR>();
			}
		}
		
		public System.Data.Linq.Table<PARTIE> PARTIE
		{
			get
			{
				return this.GetTable<PARTIE>();
			}
		}
		
		public System.Data.Linq.Table<PERSO_PARTIE> PERSO_PARTIE
		{
			get
			{
				return this.GetTable<PERSO_PARTIE>();
			}
		}
		
		public System.Data.Linq.Table<CLASSE> CLASSE
		{
			get
			{
				return this.GetTable<CLASSE>();
			}
		}
		
		public System.Data.Linq.Table<RACE> RACE
		{
			get
			{
				return this.GetTable<RACE>();
			}
		}
		
		public System.Data.Linq.Table<COMPETENCE> COMPETENCE
		{
			get
			{
				return this.GetTable<COMPETENCE>();
			}
		}
		
		public System.Data.Linq.Table<OBJET_RARE> OBJET_RARE
		{
			get
			{
				return this.GetTable<OBJET_RARE>();
			}
		}
		
		public System.Data.Linq.Table<ViewPersoPseudo> ViewPersoPseudo
		{
			get
			{
				return this.GetTable<ViewPersoPseudo>();
			}
		}
		
		public System.Data.Linq.Table<View_Partie_Perso> View_Partie_Perso
		{
			get
			{
				return this.GetTable<View_Partie_Perso>();
			}
		}
		
		public System.Data.Linq.Table<View_personnage> View_personnage
		{
			get
			{
				return this.GetTable<View_personnage>();
			}
		}
		
		public System.Data.Linq.Table<OBJET> OBJET
		{
			get
			{
				return this.GetTable<OBJET>();
			}
		}
		
		public System.Data.Linq.Table<PERSONNAGE> PERSONNAGE
		{
			get
			{
				return this.GetTable<PERSONNAGE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSO_OBJET")]
	public partial class PERSO_OBJET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_objet;
		
		private int _id_perso;
		
		private EntityRef<OBJET> _OBJET;
		
		private EntityRef<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_objetChanging(int value);
    partial void Onid_objetChanged();
    partial void Onid_persoChanging(int value);
    partial void Onid_persoChanged();
    #endregion
		
		public PERSO_OBJET()
		{
			this._OBJET = default(EntityRef<OBJET>);
			this._PERSONNAGE = default(EntityRef<PERSONNAGE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_objet", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_objet
		{
			get
			{
				return this._id_objet;
			}
			set
			{
				if ((this._id_objet != value))
				{
					if (this._OBJET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_objetChanging(value);
					this.SendPropertyChanging();
					this._id_objet = value;
					this.SendPropertyChanged("id_objet");
					this.Onid_objetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					if (this._PERSONNAGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persoChanging(value);
					this.SendPropertyChanging();
					this._id_perso = value;
					this.SendPropertyChanged("id_perso");
					this.Onid_persoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OBJET_PERSO_OBJET", Storage="_OBJET", ThisKey="id_objet", OtherKey="id_objet", IsForeignKey=true)]
		public OBJET OBJET
		{
			get
			{
				return this._OBJET.Entity;
			}
			set
			{
				OBJET previousValue = this._OBJET.Entity;
				if (((previousValue != value) 
							|| (this._OBJET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OBJET.Entity = null;
						previousValue.PERSO_OBJET.Remove(this);
					}
					this._OBJET.Entity = value;
					if ((value != null))
					{
						value.PERSO_OBJET.Add(this);
						this._id_objet = value.id_objet;
					}
					else
					{
						this._id_objet = default(int);
					}
					this.SendPropertyChanged("OBJET");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_OBJET", Storage="_PERSONNAGE", ThisKey="id_perso", OtherKey="id_perso", IsForeignKey=true)]
		public PERSONNAGE PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE.Entity;
			}
			set
			{
				PERSONNAGE previousValue = this._PERSONNAGE.Entity;
				if (((previousValue != value) 
							|| (this._PERSONNAGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERSONNAGE.Entity = null;
						previousValue.PERSO_OBJET.Remove(this);
					}
					this._PERSONNAGE.Entity = value;
					if ((value != null))
					{
						value.PERSO_OBJET.Add(this);
						this._id_perso = value.id_perso;
					}
					else
					{
						this._id_perso = default(int);
					}
					this.SendPropertyChanged("PERSONNAGE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSO_COMP")]
	public partial class PERSO_COMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_competence;
		
		private int _id_perso;
		
		private EntityRef<COMPETENCE> _COMPETENCE;
		
		private EntityRef<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_competenceChanging(int value);
    partial void Onid_competenceChanged();
    partial void Onid_persoChanging(int value);
    partial void Onid_persoChanged();
    #endregion
		
		public PERSO_COMP()
		{
			this._COMPETENCE = default(EntityRef<COMPETENCE>);
			this._PERSONNAGE = default(EntityRef<PERSONNAGE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_competence", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_competence
		{
			get
			{
				return this._id_competence;
			}
			set
			{
				if ((this._id_competence != value))
				{
					if (this._COMPETENCE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_competenceChanging(value);
					this.SendPropertyChanging();
					this._id_competence = value;
					this.SendPropertyChanged("id_competence");
					this.Onid_competenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					if (this._PERSONNAGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persoChanging(value);
					this.SendPropertyChanging();
					this._id_perso = value;
					this.SendPropertyChanged("id_perso");
					this.Onid_persoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPETENCE_PERSO_COMP", Storage="_COMPETENCE", ThisKey="id_competence", OtherKey="id_competence", IsForeignKey=true)]
		public COMPETENCE COMPETENCE
		{
			get
			{
				return this._COMPETENCE.Entity;
			}
			set
			{
				COMPETENCE previousValue = this._COMPETENCE.Entity;
				if (((previousValue != value) 
							|| (this._COMPETENCE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMPETENCE.Entity = null;
						previousValue.PERSO_COMP.Remove(this);
					}
					this._COMPETENCE.Entity = value;
					if ((value != null))
					{
						value.PERSO_COMP.Add(this);
						this._id_competence = value.id_competence;
					}
					else
					{
						this._id_competence = default(int);
					}
					this.SendPropertyChanged("COMPETENCE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_COMP", Storage="_PERSONNAGE", ThisKey="id_perso", OtherKey="id_perso", IsForeignKey=true)]
		public PERSONNAGE PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE.Entity;
			}
			set
			{
				PERSONNAGE previousValue = this._PERSONNAGE.Entity;
				if (((previousValue != value) 
							|| (this._PERSONNAGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERSONNAGE.Entity = null;
						previousValue.PERSO_COMP.Remove(this);
					}
					this._PERSONNAGE.Entity = value;
					if ((value != null))
					{
						value.PERSO_COMP.Add(this);
						this._id_perso = value.id_perso;
					}
					else
					{
						this._id_perso = default(int);
					}
					this.SendPropertyChanged("PERSONNAGE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JOUEUR")]
	public partial class JOUEUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_joueur;
		
		private string _pseudo;
		
		private string _nom;
		
		private string _prenom;
		
		private string _pass;
		
		private bool _admin;
		
		private EntitySet<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_joueurChanging(int value);
    partial void Onid_joueurChanged();
    partial void OnpseudoChanging(string value);
    partial void OnpseudoChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnadminChanging(bool value);
    partial void OnadminChanged();
    #endregion
		
		public JOUEUR()
		{
			this._PERSONNAGE = new EntitySet<PERSONNAGE>(new Action<PERSONNAGE>(this.attach_PERSONNAGE), new Action<PERSONNAGE>(this.detach_PERSONNAGE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_joueur", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_joueur
		{
			get
			{
				return this._id_joueur;
			}
			set
			{
				if ((this._id_joueur != value))
				{
					this.Onid_joueurChanging(value);
					this.SendPropertyChanging();
					this._id_joueur = value;
					this.SendPropertyChanged("id_joueur");
					this.Onid_joueurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this.OnpseudoChanging(value);
					this.SendPropertyChanging();
					this._pseudo = value;
					this.SendPropertyChanged("pseudo");
					this.OnpseudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="Bit NOT NULL")]
		public bool admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this.OnadminChanging(value);
					this.SendPropertyChanging();
					this._admin = value;
					this.SendPropertyChanged("admin");
					this.OnadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JOUEUR_PERSONNAGE", Storage="_PERSONNAGE", ThisKey="id_joueur", OtherKey="id_joueur")]
		public EntitySet<PERSONNAGE> PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE;
			}
			set
			{
				this._PERSONNAGE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.JOUEUR = this;
		}
		
		private void detach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.JOUEUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARTIE")]
	public partial class PARTIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_partie;
		
		private string _nom;
		
		private System.DateTime _date_start;
		
		private EntitySet<PERSO_PARTIE> _PERSO_PARTIE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_partieChanging(int value);
    partial void Onid_partieChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void Ondate_startChanging(System.DateTime value);
    partial void Ondate_startChanged();
    #endregion
		
		public PARTIE()
		{
			this._PERSO_PARTIE = new EntitySet<PERSO_PARTIE>(new Action<PERSO_PARTIE>(this.attach_PERSO_PARTIE), new Action<PERSO_PARTIE>(this.detach_PERSO_PARTIE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_partie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_partie
		{
			get
			{
				return this._id_partie;
			}
			set
			{
				if ((this._id_partie != value))
				{
					this.Onid_partieChanging(value);
					this.SendPropertyChanging();
					this._id_partie = value;
					this.SendPropertyChanged("id_partie");
					this.Onid_partieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_start", DbType="Date NOT NULL")]
		public System.DateTime date_start
		{
			get
			{
				return this._date_start;
			}
			set
			{
				if ((this._date_start != value))
				{
					this.Ondate_startChanging(value);
					this.SendPropertyChanging();
					this._date_start = value;
					this.SendPropertyChanged("date_start");
					this.Ondate_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PARTIE_PERSO_PARTIE", Storage="_PERSO_PARTIE", ThisKey="id_partie", OtherKey="id_partie")]
		public EntitySet<PERSO_PARTIE> PERSO_PARTIE
		{
			get
			{
				return this._PERSO_PARTIE;
			}
			set
			{
				this._PERSO_PARTIE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSO_PARTIE(PERSO_PARTIE entity)
		{
			this.SendPropertyChanging();
			entity.PARTIE = this;
		}
		
		private void detach_PERSO_PARTIE(PERSO_PARTIE entity)
		{
			this.SendPropertyChanging();
			entity.PARTIE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSO_PARTIE")]
	public partial class PERSO_PARTIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_perso;
		
		private int _id_partie;
		
		private EntityRef<PARTIE> _PARTIE;
		
		private EntityRef<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_persoChanging(int value);
    partial void Onid_persoChanged();
    partial void Onid_partieChanging(int value);
    partial void Onid_partieChanged();
    #endregion
		
		public PERSO_PARTIE()
		{
			this._PARTIE = default(EntityRef<PARTIE>);
			this._PERSONNAGE = default(EntityRef<PERSONNAGE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					if (this._PERSONNAGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persoChanging(value);
					this.SendPropertyChanging();
					this._id_perso = value;
					this.SendPropertyChanged("id_perso");
					this.Onid_persoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_partie", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_partie
		{
			get
			{
				return this._id_partie;
			}
			set
			{
				if ((this._id_partie != value))
				{
					if (this._PARTIE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_partieChanging(value);
					this.SendPropertyChanging();
					this._id_partie = value;
					this.SendPropertyChanged("id_partie");
					this.Onid_partieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PARTIE_PERSO_PARTIE", Storage="_PARTIE", ThisKey="id_partie", OtherKey="id_partie", IsForeignKey=true)]
		public PARTIE PARTIE
		{
			get
			{
				return this._PARTIE.Entity;
			}
			set
			{
				PARTIE previousValue = this._PARTIE.Entity;
				if (((previousValue != value) 
							|| (this._PARTIE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PARTIE.Entity = null;
						previousValue.PERSO_PARTIE.Remove(this);
					}
					this._PARTIE.Entity = value;
					if ((value != null))
					{
						value.PERSO_PARTIE.Add(this);
						this._id_partie = value.id_partie;
					}
					else
					{
						this._id_partie = default(int);
					}
					this.SendPropertyChanged("PARTIE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_PARTIE", Storage="_PERSONNAGE", ThisKey="id_perso", OtherKey="id_perso", IsForeignKey=true)]
		public PERSONNAGE PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE.Entity;
			}
			set
			{
				PERSONNAGE previousValue = this._PERSONNAGE.Entity;
				if (((previousValue != value) 
							|| (this._PERSONNAGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERSONNAGE.Entity = null;
						previousValue.PERSO_PARTIE.Remove(this);
					}
					this._PERSONNAGE.Entity = value;
					if ((value != null))
					{
						value.PERSO_PARTIE.Add(this);
						this._id_perso = value.id_perso;
					}
					else
					{
						this._id_perso = default(int);
					}
					this.SendPropertyChanged("PERSONNAGE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASSE")]
	public partial class CLASSE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_class;
		
		private string _nom;
		
		private int _pv;
		
		private int _force;
		
		private int _intelligence;
		
		private int _agilite;
		
		private int _initiative;
		
		private int _social;
		
		private EntitySet<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_classChanging(int value);
    partial void Onid_classChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnpvChanging(int value);
    partial void OnpvChanged();
    partial void OnforceChanging(int value);
    partial void OnforceChanged();
    partial void OnintelligenceChanging(int value);
    partial void OnintelligenceChanged();
    partial void OnagiliteChanging(int value);
    partial void OnagiliteChanged();
    partial void OninitiativeChanging(int value);
    partial void OninitiativeChanged();
    partial void OnsocialChanging(int value);
    partial void OnsocialChanged();
    #endregion
		
		public CLASSE()
		{
			this._PERSONNAGE = new EntitySet<PERSONNAGE>(new Action<PERSONNAGE>(this.attach_PERSONNAGE), new Action<PERSONNAGE>(this.detach_PERSONNAGE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_class", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_class
		{
			get
			{
				return this._id_class;
			}
			set
			{
				if ((this._id_class != value))
				{
					this.Onid_classChanging(value);
					this.SendPropertyChanging();
					this._id_class = value;
					this.SendPropertyChanged("id_class");
					this.Onid_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv", DbType="Int NOT NULL")]
		public int pv
		{
			get
			{
				return this._pv;
			}
			set
			{
				if ((this._pv != value))
				{
					this.OnpvChanging(value);
					this.SendPropertyChanging();
					this._pv = value;
					this.SendPropertyChanged("pv");
					this.OnpvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_force", DbType="Int NOT NULL")]
		public int force
		{
			get
			{
				return this._force;
			}
			set
			{
				if ((this._force != value))
				{
					this.OnforceChanging(value);
					this.SendPropertyChanging();
					this._force = value;
					this.SendPropertyChanged("force");
					this.OnforceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intelligence", DbType="Int NOT NULL")]
		public int intelligence
		{
			get
			{
				return this._intelligence;
			}
			set
			{
				if ((this._intelligence != value))
				{
					this.OnintelligenceChanging(value);
					this.SendPropertyChanging();
					this._intelligence = value;
					this.SendPropertyChanged("intelligence");
					this.OnintelligenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agilite", DbType="Int NOT NULL")]
		public int agilite
		{
			get
			{
				return this._agilite;
			}
			set
			{
				if ((this._agilite != value))
				{
					this.OnagiliteChanging(value);
					this.SendPropertyChanging();
					this._agilite = value;
					this.SendPropertyChanged("agilite");
					this.OnagiliteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiative", DbType="Int NOT NULL")]
		public int initiative
		{
			get
			{
				return this._initiative;
			}
			set
			{
				if ((this._initiative != value))
				{
					this.OninitiativeChanging(value);
					this.SendPropertyChanging();
					this._initiative = value;
					this.SendPropertyChanged("initiative");
					this.OninitiativeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social", DbType="Int NOT NULL")]
		public int social
		{
			get
			{
				return this._social;
			}
			set
			{
				if ((this._social != value))
				{
					this.OnsocialChanging(value);
					this.SendPropertyChanging();
					this._social = value;
					this.SendPropertyChanged("social");
					this.OnsocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASSE_PERSONNAGE", Storage="_PERSONNAGE", ThisKey="id_class", OtherKey="id_class")]
		public EntitySet<PERSONNAGE> PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE;
			}
			set
			{
				this._PERSONNAGE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.CLASSE = this;
		}
		
		private void detach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.CLASSE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RACE")]
	public partial class RACE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_race;
		
		private string _nom;
		
		private int _pv;
		
		private int _force;
		
		private int _intelligence;
		
		private int _agilite;
		
		private int _initiative;
		
		private int _social;
		
		private EntitySet<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_raceChanging(int value);
    partial void Onid_raceChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnpvChanging(int value);
    partial void OnpvChanged();
    partial void OnforceChanging(int value);
    partial void OnforceChanged();
    partial void OnintelligenceChanging(int value);
    partial void OnintelligenceChanged();
    partial void OnagiliteChanging(int value);
    partial void OnagiliteChanged();
    partial void OninitiativeChanging(int value);
    partial void OninitiativeChanged();
    partial void OnsocialChanging(int value);
    partial void OnsocialChanged();
    #endregion
		
		public RACE()
		{
			this._PERSONNAGE = new EntitySet<PERSONNAGE>(new Action<PERSONNAGE>(this.attach_PERSONNAGE), new Action<PERSONNAGE>(this.detach_PERSONNAGE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_race", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_race
		{
			get
			{
				return this._id_race;
			}
			set
			{
				if ((this._id_race != value))
				{
					this.Onid_raceChanging(value);
					this.SendPropertyChanging();
					this._id_race = value;
					this.SendPropertyChanged("id_race");
					this.Onid_raceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv", DbType="Int NOT NULL")]
		public int pv
		{
			get
			{
				return this._pv;
			}
			set
			{
				if ((this._pv != value))
				{
					this.OnpvChanging(value);
					this.SendPropertyChanging();
					this._pv = value;
					this.SendPropertyChanged("pv");
					this.OnpvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_force", DbType="Int NOT NULL")]
		public int force
		{
			get
			{
				return this._force;
			}
			set
			{
				if ((this._force != value))
				{
					this.OnforceChanging(value);
					this.SendPropertyChanging();
					this._force = value;
					this.SendPropertyChanged("force");
					this.OnforceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intelligence", DbType="Int NOT NULL")]
		public int intelligence
		{
			get
			{
				return this._intelligence;
			}
			set
			{
				if ((this._intelligence != value))
				{
					this.OnintelligenceChanging(value);
					this.SendPropertyChanging();
					this._intelligence = value;
					this.SendPropertyChanged("intelligence");
					this.OnintelligenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agilite", DbType="Int NOT NULL")]
		public int agilite
		{
			get
			{
				return this._agilite;
			}
			set
			{
				if ((this._agilite != value))
				{
					this.OnagiliteChanging(value);
					this.SendPropertyChanging();
					this._agilite = value;
					this.SendPropertyChanged("agilite");
					this.OnagiliteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiative", DbType="Int NOT NULL")]
		public int initiative
		{
			get
			{
				return this._initiative;
			}
			set
			{
				if ((this._initiative != value))
				{
					this.OninitiativeChanging(value);
					this.SendPropertyChanging();
					this._initiative = value;
					this.SendPropertyChanged("initiative");
					this.OninitiativeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social", DbType="Int NOT NULL")]
		public int social
		{
			get
			{
				return this._social;
			}
			set
			{
				if ((this._social != value))
				{
					this.OnsocialChanging(value);
					this.SendPropertyChanging();
					this._social = value;
					this.SendPropertyChanged("social");
					this.OnsocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RACE_PERSONNAGE", Storage="_PERSONNAGE", ThisKey="id_race", OtherKey="id_race")]
		public EntitySet<PERSONNAGE> PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE;
			}
			set
			{
				this._PERSONNAGE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.RACE = this;
		}
		
		private void detach_PERSONNAGE(PERSONNAGE entity)
		{
			this.SendPropertyChanging();
			entity.RACE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMPETENCE")]
	public partial class COMPETENCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_competence;
		
		private string _nom;
		
		private string _stat_liee;
		
		private string _valeur;
		
		private EntitySet<PERSO_COMP> _PERSO_COMP;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_competenceChanging(int value);
    partial void Onid_competenceChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void Onstat_lieeChanging(string value);
    partial void Onstat_lieeChanged();
    partial void OnvaleurChanging(string value);
    partial void OnvaleurChanged();
    #endregion
		
		public COMPETENCE()
		{
			this._PERSO_COMP = new EntitySet<PERSO_COMP>(new Action<PERSO_COMP>(this.attach_PERSO_COMP), new Action<PERSO_COMP>(this.detach_PERSO_COMP));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_competence", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_competence
		{
			get
			{
				return this._id_competence;
			}
			set
			{
				if ((this._id_competence != value))
				{
					this.Onid_competenceChanging(value);
					this.SendPropertyChanging();
					this._id_competence = value;
					this.SendPropertyChanged("id_competence");
					this.Onid_competenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_liee", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stat_liee
		{
			get
			{
				return this._stat_liee;
			}
			set
			{
				if ((this._stat_liee != value))
				{
					this.Onstat_lieeChanging(value);
					this.SendPropertyChanging();
					this._stat_liee = value;
					this.SendPropertyChanged("stat_liee");
					this.Onstat_lieeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valeur", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string valeur
		{
			get
			{
				return this._valeur;
			}
			set
			{
				if ((this._valeur != value))
				{
					this.OnvaleurChanging(value);
					this.SendPropertyChanging();
					this._valeur = value;
					this.SendPropertyChanged("valeur");
					this.OnvaleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPETENCE_PERSO_COMP", Storage="_PERSO_COMP", ThisKey="id_competence", OtherKey="id_competence")]
		public EntitySet<PERSO_COMP> PERSO_COMP
		{
			get
			{
				return this._PERSO_COMP;
			}
			set
			{
				this._PERSO_COMP.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSO_COMP(PERSO_COMP entity)
		{
			this.SendPropertyChanging();
			entity.COMPETENCE = this;
		}
		
		private void detach_PERSO_COMP(PERSO_COMP entity)
		{
			this.SendPropertyChanging();
			entity.COMPETENCE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OBJET_RARE")]
	public partial class OBJET_RARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_obj_rare;
		
		private System.Nullable<int> _id_perso;
		
		private string _nom;
		
		private string _description;
		
		private string _stats;
		
		private EntityRef<PERSONNAGE> _PERSONNAGE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_obj_rareChanging(int value);
    partial void Onid_obj_rareChanged();
    partial void Onid_persoChanging(System.Nullable<int> value);
    partial void Onid_persoChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnstatsChanging(string value);
    partial void OnstatsChanged();
    #endregion
		
		public OBJET_RARE()
		{
			this._PERSONNAGE = default(EntityRef<PERSONNAGE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_obj_rare", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_obj_rare
		{
			get
			{
				return this._id_obj_rare;
			}
			set
			{
				if ((this._id_obj_rare != value))
				{
					this.Onid_obj_rareChanging(value);
					this.SendPropertyChanging();
					this._id_obj_rare = value;
					this.SendPropertyChanged("id_obj_rare");
					this.Onid_obj_rareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int")]
		public System.Nullable<int> id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					if (this._PERSONNAGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persoChanging(value);
					this.SendPropertyChanging();
					this._id_perso = value;
					this.SendPropertyChanged("id_perso");
					this.Onid_persoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stats", DbType="VarChar(50)")]
		public string stats
		{
			get
			{
				return this._stats;
			}
			set
			{
				if ((this._stats != value))
				{
					this.OnstatsChanging(value);
					this.SendPropertyChanging();
					this._stats = value;
					this.SendPropertyChanged("stats");
					this.OnstatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_OBJET_RARE", Storage="_PERSONNAGE", ThisKey="id_perso", OtherKey="id_perso", IsForeignKey=true)]
		public PERSONNAGE PERSONNAGE
		{
			get
			{
				return this._PERSONNAGE.Entity;
			}
			set
			{
				PERSONNAGE previousValue = this._PERSONNAGE.Entity;
				if (((previousValue != value) 
							|| (this._PERSONNAGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERSONNAGE.Entity = null;
						previousValue.OBJET_RARE.Remove(this);
					}
					this._PERSONNAGE.Entity = value;
					if ((value != null))
					{
						value.OBJET_RARE.Add(this);
						this._id_perso = value.id_perso;
					}
					else
					{
						this._id_perso = default(Nullable<int>);
					}
					this.SendPropertyChanged("PERSONNAGE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewPersoPseudo")]
	public partial class ViewPersoPseudo
	{
		
		private int _id_perso;
		
		private string _nom;
		
		private int _niveau;
		
		private string _txt_long;
		
		private int _dgt_cc;
		
		private int _dgt_ad;
		
		private int _def;
		
		private string _img;
		
		private System.Nullable<int> _id_joueur;
		
		private int _id_class;
		
		private int _id_race;
		
		private System.Nullable<int> _pv;
		
		private System.Nullable<int> _force;
		
		private System.Nullable<int> _agilite;
		
		private System.Nullable<int> _intelligence;
		
		private System.Nullable<int> _initiative;
		
		private System.Nullable<int> _social;
		
		private string _pseudo;
		
		public ViewPersoPseudo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL")]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					this._id_perso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int NOT NULL")]
		public int niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this._niveau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txt_long", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string txt_long
		{
			get
			{
				return this._txt_long;
			}
			set
			{
				if ((this._txt_long != value))
				{
					this._txt_long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_cc", DbType="Int NOT NULL")]
		public int dgt_cc
		{
			get
			{
				return this._dgt_cc;
			}
			set
			{
				if ((this._dgt_cc != value))
				{
					this._dgt_cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_ad", DbType="Int NOT NULL")]
		public int dgt_ad
		{
			get
			{
				return this._dgt_ad;
			}
			set
			{
				if ((this._dgt_ad != value))
				{
					this._dgt_ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_def", DbType="Int NOT NULL")]
		public int def
		{
			get
			{
				return this._def;
			}
			set
			{
				if ((this._def != value))
				{
					this._def = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(50)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_joueur", DbType="Int")]
		public System.Nullable<int> id_joueur
		{
			get
			{
				return this._id_joueur;
			}
			set
			{
				if ((this._id_joueur != value))
				{
					this._id_joueur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_class", DbType="Int NOT NULL")]
		public int id_class
		{
			get
			{
				return this._id_class;
			}
			set
			{
				if ((this._id_class != value))
				{
					this._id_class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_race", DbType="Int NOT NULL")]
		public int id_race
		{
			get
			{
				return this._id_race;
			}
			set
			{
				if ((this._id_race != value))
				{
					this._id_race = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv", DbType="Int")]
		public System.Nullable<int> pv
		{
			get
			{
				return this._pv;
			}
			set
			{
				if ((this._pv != value))
				{
					this._pv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_force", DbType="Int")]
		public System.Nullable<int> force
		{
			get
			{
				return this._force;
			}
			set
			{
				if ((this._force != value))
				{
					this._force = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agilite", DbType="Int")]
		public System.Nullable<int> agilite
		{
			get
			{
				return this._agilite;
			}
			set
			{
				if ((this._agilite != value))
				{
					this._agilite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intelligence", DbType="Int")]
		public System.Nullable<int> intelligence
		{
			get
			{
				return this._intelligence;
			}
			set
			{
				if ((this._intelligence != value))
				{
					this._intelligence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiative", DbType="Int")]
		public System.Nullable<int> initiative
		{
			get
			{
				return this._initiative;
			}
			set
			{
				if ((this._initiative != value))
				{
					this._initiative = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social", DbType="Int")]
		public System.Nullable<int> social
		{
			get
			{
				return this._social;
			}
			set
			{
				if ((this._social != value))
				{
					this._social = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this._pseudo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Partie_Perso")]
	public partial class View_Partie_Perso
	{
		
		private string _nom;
		
		private string _Expr1;
		
		private int _id_perso;
		
		private System.Nullable<int> _id_joueur;
		
		public View_Partie_Perso()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL")]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					this._id_perso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_joueur", DbType="Int")]
		public System.Nullable<int> id_joueur
		{
			get
			{
				return this._id_joueur;
			}
			set
			{
				if ((this._id_joueur != value))
				{
					this._id_joueur = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_personnage")]
	public partial class View_personnage
	{
		
		private string _nom;
		
		private int _niveau;
		
		private string _Expr1;
		
		private string _pseudo;
		
		private string _Expr2;
		
		private int _dgt_cc;
		
		private int _dgt_ad;
		
		private int _def;
		
		private int _id_perso;
		
		private int _id_joueur;
		
		private System.Nullable<int> _pv;
		
		private System.Nullable<int> _force;
		
		private System.Nullable<int> _agilite;
		
		private System.Nullable<int> _intelligence;
		
		private System.Nullable<int> _initiative;
		
		private System.Nullable<int> _social;
		
		private string _txt_long;
		
		private string _img;
		
		public View_personnage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int NOT NULL")]
		public int niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this._niveau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this._pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expr2
		{
			get
			{
				return this._Expr2;
			}
			set
			{
				if ((this._Expr2 != value))
				{
					this._Expr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_cc", DbType="Int NOT NULL")]
		public int dgt_cc
		{
			get
			{
				return this._dgt_cc;
			}
			set
			{
				if ((this._dgt_cc != value))
				{
					this._dgt_cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_ad", DbType="Int NOT NULL")]
		public int dgt_ad
		{
			get
			{
				return this._dgt_ad;
			}
			set
			{
				if ((this._dgt_ad != value))
				{
					this._dgt_ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_def", DbType="Int NOT NULL")]
		public int def
		{
			get
			{
				return this._def;
			}
			set
			{
				if ((this._def != value))
				{
					this._def = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", DbType="Int NOT NULL")]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					this._id_perso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_joueur", DbType="Int NOT NULL")]
		public int id_joueur
		{
			get
			{
				return this._id_joueur;
			}
			set
			{
				if ((this._id_joueur != value))
				{
					this._id_joueur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv", DbType="Int")]
		public System.Nullable<int> pv
		{
			get
			{
				return this._pv;
			}
			set
			{
				if ((this._pv != value))
				{
					this._pv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_force", DbType="Int")]
		public System.Nullable<int> force
		{
			get
			{
				return this._force;
			}
			set
			{
				if ((this._force != value))
				{
					this._force = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agilite", DbType="Int")]
		public System.Nullable<int> agilite
		{
			get
			{
				return this._agilite;
			}
			set
			{
				if ((this._agilite != value))
				{
					this._agilite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intelligence", DbType="Int")]
		public System.Nullable<int> intelligence
		{
			get
			{
				return this._intelligence;
			}
			set
			{
				if ((this._intelligence != value))
				{
					this._intelligence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiative", DbType="Int")]
		public System.Nullable<int> initiative
		{
			get
			{
				return this._initiative;
			}
			set
			{
				if ((this._initiative != value))
				{
					this._initiative = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social", DbType="Int")]
		public System.Nullable<int> social
		{
			get
			{
				return this._social;
			}
			set
			{
				if ((this._social != value))
				{
					this._social = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txt_long", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string txt_long
		{
			get
			{
				return this._txt_long;
			}
			set
			{
				if ((this._txt_long != value))
				{
					this._txt_long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(50)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OBJET")]
	public partial class OBJET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_objet;
		
		private string _nom;
		
		private int _valeur;
		
		private string _stat_liee;
		
		private EntitySet<PERSO_OBJET> _PERSO_OBJET;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_objetChanging(int value);
    partial void Onid_objetChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnvaleurChanging(int value);
    partial void OnvaleurChanged();
    partial void Onstat_lieeChanging(string value);
    partial void Onstat_lieeChanged();
    #endregion
		
		public OBJET()
		{
			this._PERSO_OBJET = new EntitySet<PERSO_OBJET>(new Action<PERSO_OBJET>(this.attach_PERSO_OBJET), new Action<PERSO_OBJET>(this.detach_PERSO_OBJET));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_objet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_objet
		{
			get
			{
				return this._id_objet;
			}
			set
			{
				if ((this._id_objet != value))
				{
					this.Onid_objetChanging(value);
					this.SendPropertyChanging();
					this._id_objet = value;
					this.SendPropertyChanged("id_objet");
					this.Onid_objetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valeur", DbType="Int NOT NULL")]
		public int valeur
		{
			get
			{
				return this._valeur;
			}
			set
			{
				if ((this._valeur != value))
				{
					this.OnvaleurChanging(value);
					this.SendPropertyChanging();
					this._valeur = value;
					this.SendPropertyChanged("valeur");
					this.OnvaleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_liee", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stat_liee
		{
			get
			{
				return this._stat_liee;
			}
			set
			{
				if ((this._stat_liee != value))
				{
					this.Onstat_lieeChanging(value);
					this.SendPropertyChanging();
					this._stat_liee = value;
					this.SendPropertyChanged("stat_liee");
					this.Onstat_lieeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OBJET_PERSO_OBJET", Storage="_PERSO_OBJET", ThisKey="id_objet", OtherKey="id_objet")]
		public EntitySet<PERSO_OBJET> PERSO_OBJET
		{
			get
			{
				return this._PERSO_OBJET;
			}
			set
			{
				this._PERSO_OBJET.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSO_OBJET(PERSO_OBJET entity)
		{
			this.SendPropertyChanging();
			entity.OBJET = this;
		}
		
		private void detach_PERSO_OBJET(PERSO_OBJET entity)
		{
			this.SendPropertyChanging();
			entity.OBJET = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSONNAGE")]
	public partial class PERSONNAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_perso;
		
		private string _nom;
		
		private int _niveau;
		
		private string _txt_long;
		
		private int _dgt_cc;
		
		private int _dgt_ad;
		
		private int _def;
		
		private string _img;
		
		private System.Nullable<int> _id_joueur;
		
		private int _id_class;
		
		private int _id_race;
		
		private System.Nullable<int> _pv;
		
		private System.Nullable<int> _force;
		
		private System.Nullable<int> _agilite;
		
		private System.Nullable<int> _intelligence;
		
		private System.Nullable<int> _initiative;
		
		private System.Nullable<int> _social;
		
		private System.Nullable<bool> _pnj;
		
		private EntitySet<PERSO_OBJET> _PERSO_OBJET;
		
		private EntitySet<PERSO_COMP> _PERSO_COMP;
		
		private EntitySet<PERSO_PARTIE> _PERSO_PARTIE;
		
		private EntitySet<OBJET_RARE> _OBJET_RARE;
		
		private EntityRef<CLASSE> _CLASSE;
		
		private EntityRef<JOUEUR> _JOUEUR;
		
		private EntityRef<RACE> _RACE;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_persoChanging(int value);
    partial void Onid_persoChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnniveauChanging(int value);
    partial void OnniveauChanged();
    partial void Ontxt_longChanging(string value);
    partial void Ontxt_longChanged();
    partial void Ondgt_ccChanging(int value);
    partial void Ondgt_ccChanged();
    partial void Ondgt_adChanging(int value);
    partial void Ondgt_adChanged();
    partial void OndefChanging(int value);
    partial void OndefChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void Onid_joueurChanging(System.Nullable<int> value);
    partial void Onid_joueurChanged();
    partial void Onid_classChanging(int value);
    partial void Onid_classChanged();
    partial void Onid_raceChanging(int value);
    partial void Onid_raceChanged();
    partial void OnpvChanging(System.Nullable<int> value);
    partial void OnpvChanged();
    partial void OnforceChanging(System.Nullable<int> value);
    partial void OnforceChanged();
    partial void OnagiliteChanging(System.Nullable<int> value);
    partial void OnagiliteChanged();
    partial void OnintelligenceChanging(System.Nullable<int> value);
    partial void OnintelligenceChanged();
    partial void OninitiativeChanging(System.Nullable<int> value);
    partial void OninitiativeChanged();
    partial void OnsocialChanging(System.Nullable<int> value);
    partial void OnsocialChanged();
    partial void OnpnjChanging(System.Nullable<bool> value);
    partial void OnpnjChanged();
    #endregion
		
		public PERSONNAGE()
		{
			this._PERSO_OBJET = new EntitySet<PERSO_OBJET>(new Action<PERSO_OBJET>(this.attach_PERSO_OBJET), new Action<PERSO_OBJET>(this.detach_PERSO_OBJET));
			this._PERSO_COMP = new EntitySet<PERSO_COMP>(new Action<PERSO_COMP>(this.attach_PERSO_COMP), new Action<PERSO_COMP>(this.detach_PERSO_COMP));
			this._PERSO_PARTIE = new EntitySet<PERSO_PARTIE>(new Action<PERSO_PARTIE>(this.attach_PERSO_PARTIE), new Action<PERSO_PARTIE>(this.detach_PERSO_PARTIE));
			this._OBJET_RARE = new EntitySet<OBJET_RARE>(new Action<OBJET_RARE>(this.attach_OBJET_RARE), new Action<OBJET_RARE>(this.detach_OBJET_RARE));
			this._CLASSE = default(EntityRef<CLASSE>);
			this._JOUEUR = default(EntityRef<JOUEUR>);
			this._RACE = default(EntityRef<RACE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_perso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_perso
		{
			get
			{
				return this._id_perso;
			}
			set
			{
				if ((this._id_perso != value))
				{
					this.Onid_persoChanging(value);
					this.SendPropertyChanging();
					this._id_perso = value;
					this.SendPropertyChanged("id_perso");
					this.Onid_persoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int NOT NULL")]
		public int niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this.OnniveauChanging(value);
					this.SendPropertyChanging();
					this._niveau = value;
					this.SendPropertyChanged("niveau");
					this.OnniveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txt_long", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string txt_long
		{
			get
			{
				return this._txt_long;
			}
			set
			{
				if ((this._txt_long != value))
				{
					this.Ontxt_longChanging(value);
					this.SendPropertyChanging();
					this._txt_long = value;
					this.SendPropertyChanged("txt_long");
					this.Ontxt_longChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_cc", DbType="Int NOT NULL")]
		public int dgt_cc
		{
			get
			{
				return this._dgt_cc;
			}
			set
			{
				if ((this._dgt_cc != value))
				{
					this.Ondgt_ccChanging(value);
					this.SendPropertyChanging();
					this._dgt_cc = value;
					this.SendPropertyChanged("dgt_cc");
					this.Ondgt_ccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dgt_ad", DbType="Int NOT NULL")]
		public int dgt_ad
		{
			get
			{
				return this._dgt_ad;
			}
			set
			{
				if ((this._dgt_ad != value))
				{
					this.Ondgt_adChanging(value);
					this.SendPropertyChanging();
					this._dgt_ad = value;
					this.SendPropertyChanged("dgt_ad");
					this.Ondgt_adChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_def", DbType="Int NOT NULL")]
		public int def
		{
			get
			{
				return this._def;
			}
			set
			{
				if ((this._def != value))
				{
					this.OndefChanging(value);
					this.SendPropertyChanging();
					this._def = value;
					this.SendPropertyChanged("def");
					this.OndefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_joueur", DbType="Int")]
		public System.Nullable<int> id_joueur
		{
			get
			{
				return this._id_joueur;
			}
			set
			{
				if ((this._id_joueur != value))
				{
					if (this._JOUEUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_joueurChanging(value);
					this.SendPropertyChanging();
					this._id_joueur = value;
					this.SendPropertyChanged("id_joueur");
					this.Onid_joueurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_class", DbType="Int NOT NULL")]
		public int id_class
		{
			get
			{
				return this._id_class;
			}
			set
			{
				if ((this._id_class != value))
				{
					if (this._CLASSE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_classChanging(value);
					this.SendPropertyChanging();
					this._id_class = value;
					this.SendPropertyChanged("id_class");
					this.Onid_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_race", DbType="Int NOT NULL")]
		public int id_race
		{
			get
			{
				return this._id_race;
			}
			set
			{
				if ((this._id_race != value))
				{
					if (this._RACE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_raceChanging(value);
					this.SendPropertyChanging();
					this._id_race = value;
					this.SendPropertyChanged("id_race");
					this.Onid_raceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv", DbType="Int")]
		public System.Nullable<int> pv
		{
			get
			{
				return this._pv;
			}
			set
			{
				if ((this._pv != value))
				{
					this.OnpvChanging(value);
					this.SendPropertyChanging();
					this._pv = value;
					this.SendPropertyChanged("pv");
					this.OnpvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_force", DbType="Int")]
		public System.Nullable<int> force
		{
			get
			{
				return this._force;
			}
			set
			{
				if ((this._force != value))
				{
					this.OnforceChanging(value);
					this.SendPropertyChanging();
					this._force = value;
					this.SendPropertyChanged("force");
					this.OnforceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agilite", DbType="Int")]
		public System.Nullable<int> agilite
		{
			get
			{
				return this._agilite;
			}
			set
			{
				if ((this._agilite != value))
				{
					this.OnagiliteChanging(value);
					this.SendPropertyChanging();
					this._agilite = value;
					this.SendPropertyChanged("agilite");
					this.OnagiliteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intelligence", DbType="Int")]
		public System.Nullable<int> intelligence
		{
			get
			{
				return this._intelligence;
			}
			set
			{
				if ((this._intelligence != value))
				{
					this.OnintelligenceChanging(value);
					this.SendPropertyChanging();
					this._intelligence = value;
					this.SendPropertyChanged("intelligence");
					this.OnintelligenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiative", DbType="Int")]
		public System.Nullable<int> initiative
		{
			get
			{
				return this._initiative;
			}
			set
			{
				if ((this._initiative != value))
				{
					this.OninitiativeChanging(value);
					this.SendPropertyChanging();
					this._initiative = value;
					this.SendPropertyChanged("initiative");
					this.OninitiativeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social", DbType="Int")]
		public System.Nullable<int> social
		{
			get
			{
				return this._social;
			}
			set
			{
				if ((this._social != value))
				{
					this.OnsocialChanging(value);
					this.SendPropertyChanging();
					this._social = value;
					this.SendPropertyChanged("social");
					this.OnsocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnj", DbType="Bit")]
		public System.Nullable<bool> pnj
		{
			get
			{
				return this._pnj;
			}
			set
			{
				if ((this._pnj != value))
				{
					this.OnpnjChanging(value);
					this.SendPropertyChanging();
					this._pnj = value;
					this.SendPropertyChanged("pnj");
					this.OnpnjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_OBJET", Storage="_PERSO_OBJET", ThisKey="id_perso", OtherKey="id_perso")]
		public EntitySet<PERSO_OBJET> PERSO_OBJET
		{
			get
			{
				return this._PERSO_OBJET;
			}
			set
			{
				this._PERSO_OBJET.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_COMP", Storage="_PERSO_COMP", ThisKey="id_perso", OtherKey="id_perso")]
		public EntitySet<PERSO_COMP> PERSO_COMP
		{
			get
			{
				return this._PERSO_COMP;
			}
			set
			{
				this._PERSO_COMP.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_PERSO_PARTIE", Storage="_PERSO_PARTIE", ThisKey="id_perso", OtherKey="id_perso")]
		public EntitySet<PERSO_PARTIE> PERSO_PARTIE
		{
			get
			{
				return this._PERSO_PARTIE;
			}
			set
			{
				this._PERSO_PARTIE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONNAGE_OBJET_RARE", Storage="_OBJET_RARE", ThisKey="id_perso", OtherKey="id_perso")]
		public EntitySet<OBJET_RARE> OBJET_RARE
		{
			get
			{
				return this._OBJET_RARE;
			}
			set
			{
				this._OBJET_RARE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASSE_PERSONNAGE", Storage="_CLASSE", ThisKey="id_class", OtherKey="id_class", IsForeignKey=true)]
		public CLASSE CLASSE
		{
			get
			{
				return this._CLASSE.Entity;
			}
			set
			{
				CLASSE previousValue = this._CLASSE.Entity;
				if (((previousValue != value) 
							|| (this._CLASSE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASSE.Entity = null;
						previousValue.PERSONNAGE.Remove(this);
					}
					this._CLASSE.Entity = value;
					if ((value != null))
					{
						value.PERSONNAGE.Add(this);
						this._id_class = value.id_class;
					}
					else
					{
						this._id_class = default(int);
					}
					this.SendPropertyChanged("CLASSE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JOUEUR_PERSONNAGE", Storage="_JOUEUR", ThisKey="id_joueur", OtherKey="id_joueur", IsForeignKey=true)]
		public JOUEUR JOUEUR
		{
			get
			{
				return this._JOUEUR.Entity;
			}
			set
			{
				JOUEUR previousValue = this._JOUEUR.Entity;
				if (((previousValue != value) 
							|| (this._JOUEUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JOUEUR.Entity = null;
						previousValue.PERSONNAGE.Remove(this);
					}
					this._JOUEUR.Entity = value;
					if ((value != null))
					{
						value.PERSONNAGE.Add(this);
						this._id_joueur = value.id_joueur;
					}
					else
					{
						this._id_joueur = default(Nullable<int>);
					}
					this.SendPropertyChanged("JOUEUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RACE_PERSONNAGE", Storage="_RACE", ThisKey="id_race", OtherKey="id_race", IsForeignKey=true)]
		public RACE RACE
		{
			get
			{
				return this._RACE.Entity;
			}
			set
			{
				RACE previousValue = this._RACE.Entity;
				if (((previousValue != value) 
							|| (this._RACE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RACE.Entity = null;
						previousValue.PERSONNAGE.Remove(this);
					}
					this._RACE.Entity = value;
					if ((value != null))
					{
						value.PERSONNAGE.Add(this);
						this._id_race = value.id_race;
					}
					else
					{
						this._id_race = default(int);
					}
					this.SendPropertyChanged("RACE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSO_OBJET(PERSO_OBJET entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = this;
		}
		
		private void detach_PERSO_OBJET(PERSO_OBJET entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = null;
		}
		
		private void attach_PERSO_COMP(PERSO_COMP entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = this;
		}
		
		private void detach_PERSO_COMP(PERSO_COMP entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = null;
		}
		
		private void attach_PERSO_PARTIE(PERSO_PARTIE entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = this;
		}
		
		private void detach_PERSO_PARTIE(PERSO_PARTIE entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = null;
		}
		
		private void attach_OBJET_RARE(OBJET_RARE entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = this;
		}
		
		private void detach_OBJET_RARE(OBJET_RARE entity)
		{
			this.SendPropertyChanging();
			entity.PERSONNAGE = null;
		}
	}
}
#pragma warning restore 1591
